# Generated by Django 4.1.2 on 2022-10-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=128, verbose_name="id")),
                ("email", models.EmailField(max_length=128, verbose_name="email")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입날짜"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막수정일"),
                ),
                ("color", models.CharField(max_length=128, verbose_name="color")),
            ],
            options={"db_table": "members",},
        ),
    ]
