# Generated by Django 4.1.2 on 2022-10-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입날짜"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막수정일"),
                ),
                ("visit_count", models.IntegerField(default=1, verbose_name="방문 횟수")),
                (
                    "color",
                    models.CharField(max_length=128, null=True, verbose_name="color"),
                ),
            ],
            options={"db_table": "members",},
        ),
    ]
